services:
  postgresdb:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: MatchTFEDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  matchtfe:
    image: ${DOCKER_REGISTRY-}matchtfe
    build:
      context: .
      dockerfile: MatchTFE/MatchTFE/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_HTTP_PORTS=8080
      - GATEWAY_BASE_URL=https://${BASE_HOST}/
    volumes:
      - matchtfe_dataprotection:/root/.aspnet/DataProtection-Keys

  apigateway:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert.pem:/etc/ssl/certs/cert.pem:ro
      - ./matchtfe.pem:/etc/ssl/private/matchtfe.pem:ro
    depends_on:
      - matchtfe
      - authservice
      - userservice
      - matchservice

  authservice:
    image: ${DOCKER_REGISTRY-}authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - FRONTEND_ORIGIN=https://${BASE_HOST}
      - ConnectionStrings__DbConnection=Host=postgresdb;Port=5432;Database=MatchTFEDb;Username=postgres;Password=${DB_PASSWORD}
      - USER_SERVICE_BASE_URL=http://userservice:8080/
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__RefreshSecret=${REFRESH_SECRET}
      - JwtSettings__Issuer=MatchTFE_AuthService
      - JwtSettings__Audience=MatchTFE_Clients
    depends_on:
      - postgresdb
      - userservice

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - FRONTEND_ORIGIN=https://${BASE_HOST}
      - ConnectionStrings__DbConnection=Host=postgresdb;Port=5432;Database=MatchTFEDb;Username=postgres;Password=${DB_PASSWORD}
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=MatchTFE_AuthService
      - JwtSettings__Audience=MatchTFE_Clients
    depends_on:
      - postgresdb
      - matchservice

  matchservice:
    image: ${DOCKER_REGISTRY-}matchservice
    build:
      context: .
      dockerfile: MatchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - FRONTEND_ORIGIN=https://${BASE_HOST}
      - ConnectionStrings__DbConnection=Host=postgresdb;Port=5432;Database=MatchTFEDb;Username=postgres;Password=${DB_PASSWORD}
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=MatchTFE_AuthService
      - JwtSettings__Audience=MatchTFE_Clients
    depends_on:
      - postgresdb

volumes:
  postgres_data:
  matchtfe_dataprotection:

