// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.Data;

#nullable disable

namespace UserService.Data.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20260602135651_UserUpdateRemoveMigrations")]
    partial class UserUpdateRemoveMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TFELibrary.Data.StudentSkill", b =>
                {
                    b.Property<string>("StudentProfileId")
                        .HasColumnType("text");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("UserProfileUserId")
                        .HasColumnType("text");

                    b.HasKey("StudentProfileId", "TagId");

                    b.HasIndex("TagId");

                    b.HasIndex("UserProfileUserId");

                    b.ToTable("StudentSkill", (string)null);
                });

            modelBuilder.Entity("TFELibrary.Data.TFEProposal", b =>
                {
                    b.Property<string>("OriginUserId")
                        .HasColumnType("text");

                    b.Property<int>("TfeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("OriginUserId", "TfeId");

                    b.ToTable("TfeProposal", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("TFELibrary.Data.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Tag", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("TFELibrary.Data.UserInterest", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.Property<string>("UserProfileId")
                        .HasColumnType("text");

                    b.HasKey("TagId", "UserProfileId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("UserInterest", (string)null);
                });

            modelBuilder.Entity("TFELibrary.Data.UserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("AcademicYear")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("OfficeLocation")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfile", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("UserService.Data.UserDbContext+AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("TFELibrary.Data.StudentSkill", b =>
                {
                    b.HasOne("TFELibrary.Data.UserProfile", "StudentProfile")
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TFELibrary.Data.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TFELibrary.Data.UserProfile", null)
                        .WithMany("StudentSkills")
                        .HasForeignKey("UserProfileUserId");

                    b.Navigation("StudentProfile");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("TFELibrary.Data.TFEProposal", b =>
                {
                    b.HasOne("TFELibrary.Data.UserProfile", "OriginUser")
                        .WithMany("TfeProposals")
                        .HasForeignKey("OriginUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginUser");
                });

            modelBuilder.Entity("TFELibrary.Data.UserInterest", b =>
                {
                    b.HasOne("TFELibrary.Data.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TFELibrary.Data.UserProfile", "UserProfile")
                        .WithMany("UserInterests")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("TFELibrary.Data.UserProfile", b =>
                {
                    b.HasOne("UserService.Data.UserDbContext+AspNetUser", null)
                        .WithOne()
                        .HasForeignKey("TFELibrary.Data.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TFELibrary.Data.UserProfile", b =>
                {
                    b.Navigation("StudentSkills");

                    b.Navigation("TfeProposals");

                    b.Navigation("UserInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
