// <auto-generated />
using System;
using MatchService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MatchService.Data.Migrations
{
    [DbContext(typeof(MatchDbContext))]
    [Migration("20260605181328_DropInterestProposal")]
    partial class DropInterestProposal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TFELibrary.Data.TFE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateOnly>("EstimatedDelivery")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Tfe");
                });

            modelBuilder.Entity("TFELibrary.Data.TFEProposal", b =>
                {
                    b.Property<string>("OriginUserId")
                        .HasColumnType("text");

                    b.Property<int>("TfeId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("OriginUserId", "TfeId");

                    b.HasIndex("TfeId");

                    b.ToTable("TfeProposal");
                });

            modelBuilder.Entity("TFELibrary.Data.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tag", (string)null);
                });

            modelBuilder.Entity("TFELibrary.Data.TfeRequiredSkill", b =>
                {
                    b.Property<int>("TfeId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("TfeId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TfeRequiredSkill", (string)null);
                });

            modelBuilder.Entity("TFELibrary.Data.TfeTopic", b =>
                {
                    b.Property<int>("TfeId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("TfeId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TfeTopic", (string)null);
                });

            modelBuilder.Entity("TFELibrary.Data.UserInterest", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.Property<string>("UserProfileId")
                        .HasColumnType("text");

                    b.HasKey("TagId", "UserProfileId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("UserInterest", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("TFELibrary.Data.UserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("AcademicYear")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsSuspended")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("OfficeLocation")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("UserProfile", (string)null);
                });

            modelBuilder.Entity("TFELibrary.Data.TFE", b =>
                {
                    b.HasOne("TFELibrary.Data.UserProfile", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("TFELibrary.Data.TFEProposal", b =>
                {
                    b.HasOne("TFELibrary.Data.UserProfile", "OriginUser")
                        .WithMany("TfeProposals")
                        .HasForeignKey("OriginUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TFELibrary.Data.TFE", "Tfe")
                        .WithMany("Proposals")
                        .HasForeignKey("TfeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginUser");

                    b.Navigation("Tfe");
                });

            modelBuilder.Entity("TFELibrary.Data.TfeRequiredSkill", b =>
                {
                    b.HasOne("TFELibrary.Data.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TFELibrary.Data.TFE", "Tfe")
                        .WithMany("RequiredSkills")
                        .HasForeignKey("TfeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Tfe");
                });

            modelBuilder.Entity("TFELibrary.Data.TfeTopic", b =>
                {
                    b.HasOne("TFELibrary.Data.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TFELibrary.Data.TFE", "Tfe")
                        .WithMany()
                        .HasForeignKey("TfeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Tfe");
                });

            modelBuilder.Entity("TFELibrary.Data.UserInterest", b =>
                {
                    b.HasOne("TFELibrary.Data.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TFELibrary.Data.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("TFELibrary.Data.TFE", b =>
                {
                    b.Navigation("Proposals");

                    b.Navigation("RequiredSkills");
                });

            modelBuilder.Entity("TFELibrary.Data.UserProfile", b =>
                {
                    b.Navigation("TfeProposals");
                });
#pragma warning restore 612, 618
        }
    }
}
